notifications:
  commits: commits@synapse.apache.org
  pullrequests: dev@synapse.apache.org
  jobs: dev@synapse.apache.org
  jira_options: link label comment
github:
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
