# This is a workflow to build master at midnight

name: Synapse Daily Build

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        
      - name: Setup java 7
        uses: actions/setup-java@v1
        with:
          java-version: 7

      - name: Cache maven artifacts
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Build Synapse
        run: mvn clean install
