# This is a workflow to build master at midnight

name: Synapse Daily Test Build

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [ 8 ]

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Caches maven artifacts
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Maven Package
      run: mvn clean package

    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}
        path: modules/distribution/target/synapse-*.zip

